version: 2
registries:
  maven-artifactory:
    type: maven-repository
    url: https://abhidutta07.jfrog.io/artifactory/maven-remote/
    username: ${{secrets.JFROG_USER}}
    password: ${{secrets.JFORG_TOKEN}}
 
updates:
  - package-ecosystem: "maven"
    directory: "/"
    registries:
      - maven-artifactory
    schedule:
      interval: "daily"
