version: 2
registries:
  maven-artifactory:
    type: maven-repository
    url: http://localhost:8081/repository/abhi-maven-nexus/
    username: ${{secrets.JFROG_USER}}
    password: ${{secrets.JFORG_TOKEN}}
 
updates:
  - package-ecosystem: "maven"
    directory: "/"
    registries:
      - maven-artifactory
    schedule:
      interval: "daily"
