version: 2
registries:
  maven-artifactory:
    type: maven-repository
    url: https://abhidutta.jfrog.io
    username: ${{secrets.JFROG_USER}}
    password: ${{secrets.JFORG_TOKEN}}
 
updates:
  - package-ecosystem: "maven"
    directory: "/"
    registries:
      - maven-artifactory
    schedule:
      interval: "daily"
